# Generated by Django 5.2.1 on 2025-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_pruneorderdetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruneorderdetails',
            name='category',
            field=models.CharField(null=True),
        ),
    ]
