# Generated by Django 5.2.1 on 2025-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_pruneorderdetails_coupon_applies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruneorderdetails',
            old_name='coupon_applies',
            new_name='coupon_code',
        ),
    ]
