# Generated by Django 5.2.1 on 2025-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_rename_coupon_applies_pruneorderdetails_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruneorderdetails',
            name='procesing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
