# Generated by Django 5.2.1 on 2025-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_pruneorderdetails_procesing_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruneorderdetails',
            name='payment_method',
            field=models.CharField(choices=[('Unified Payments', 'Unified Payments'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI')], default='cod', max_length=20),
        ),
    ]
