# Generated by Django 5.2.1 on 2025-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_pruneorderdetails_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruneorderdetails',
            name='payment_method',
            field=models.CharField(choices=[('Unified Payments', 'Unified Payments'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Any', 'Any')], default='cod', max_length=20),
        ),
    ]
