# Generated by Django 5.2.1 on 2025-05-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_pruneorderdetails_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruneorderdetails',
            old_name='order_id',
            new_name='order_by',
        ),
    ]
