# Generated by Django 5.2.1 on 2025-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_rename_order_id_pruneorderdetails_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruneorderdetails',
            name='category',
            field=models.CharField(null=True),
        ),
    ]
