# Generated by Django 5.2.1 on 2025-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Latest Gadgets', 'Latest Gadgets'), ('Mobile Phones & Cool Tricks', 'Mobile Phones & Cool Tricks'), ('Latest Tech News', 'Latest Tech News'), ('Trending', 'Trending'), ('Latest Games', 'Latest Games'), ('Reviews', 'Reviews'), ('Tech News', 'Tech News'), ('Forex', 'Forex'), ('News', 'News')], max_length=50)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
