# Generated by Django 5.2.1 on 2025-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_bolg_url_name_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='bolg_url_name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
