# Generated by Django 5.2.1 on 2025-05-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_bolg_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='bolg_url_name',
            new_name='blog_url_name',
        ),
    ]
