# Generated by Django 5.2.1 on 2025-05-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_bolg_url_name_blogpost_blog_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_url_name', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
