# Generated by Django 5.2.1 on 2025-05-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='featured_image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='blog_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='travel', max_length=50),
        ),
    ]
