# Generated by Django 5.2.1 on 2025-05-27 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(unique=True)),
                ('category', models.CharField(choices=[('india_sim', 'India SIM'), ('e_sim', 'E-SIM'), ('bills', 'Bills')], max_length=20)),
                ('resolution_message', models.TextField(blank=True, null=True)),
                ('issue_description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
