# Generated by Django 5.2.1 on 2025-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolution_message',
        ),
    ]
