# Generated by Django 5.2.1 on 2025-05-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0002_remove_ticket_resolution_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
