# Generated by Django 5.2.1 on 2025-05-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0004_ticket_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolved_by',
            field=models.EmailField(max_length=254),
        ),
    ]
