# Generated by Django 5.2.1 on 2025-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0006_alter_ticket_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolved_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
