# Generated by Django 5.2.1 on 2025-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0008_alter_ticket_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_id',
            field=models.CharField(unique=True),
        ),
    ]
