# Generated by Django 5.2.1 on 2025-05-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_pruneorderdetails_payment_method'),
        ('raise_ticket', '0009_alter_ticket_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.pruneorderdetails'),
        ),
    ]
