# Generated by Django 5.2.1 on 2025-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0010_alter_ticket_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=70),
        ),
    ]
