# Generated by Django 5.2.1 on 2025-05-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0012_ticket_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ip_address',
        ),
    ]
