# Generated by Django 5.2.1 on 2025-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_ticket', '0013_remove_ticket_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
